### ISSUE TITLE
TODO : Improvements

### ISSUE THREAD

**Issue by Reichidad** [Reichidad/react-tutorial#1]
- [x] 이동 기록 목록에서 특정 형식(행, 열)으로 각 이동의 위치를 표시해주세요.
- [x] 이동 목록에서 현재 선택된 아이템을 굵게 표시해주세요.
- [x] 사각형들을 만들 때 하드코딩 대신에 두 개의 반복문을 사용하도록 Board를 다시 작성해주세요.
- [x] 오름차순이나 내림차순으로 이동을 정렬하도록 토글 버튼을 추가해주세요.
- [x] 승자가 정해지면 승부의 원인이 된 세 개의 사각형을 강조해주세요.
- [x] 승자가 없는 경우 무승부라는 메시지를 표시해주세요.
